### ISSUE TITLE
include LICENSE text

### ISSUE THREAD

**Issue by igor-raits** [sharkdp/content_inspector#3]
This is requirement for Apache-2.0 license and it simplifies packaging of tihs crate for linux distributions.

Thanks in advance!

**Comment by sharkdp** [comment]
I have added LICENSE-MIT and LICENSE-APACHE to the repository. Is a new version required?

**Comment by igor-raits** [comment]
it would be very appreciated ;)

**Comment by sharkdp** [comment]
Done.

**Comment by igor-raits** [comment]
Thanks, much appreciated!

https://koji.fedoraproject.org/koji/packageinfo?packageID=27730

**Comment by sharkdp** [comment]
Cool, thank you!
